### ISSUE TITLE
add analysis of enhancer/silencer

### ISSUE THREAD

**Issue by MartinKahabka** [MartinKahabka/ClIntKahabka#49]
instead of using the positions of promoter regions given by EDPnew use data from EnhancerAtlas and SilencerDB

see #48 for more information and the adding of the data

depends on #52 

To-Dos

- [x] update structure of pipeline #55
- [x] add new process that filters datasets based on given files with gene names #54 
- [x] update the pipeline script #56

**Comment by MartinKahabka** [comment]
decided on manual parsing, using known format (see below)
=> only once per dataset, no additional runtime when pipeline is executed

Do-Tos

- [ ] Parse datasets to format
- [ ] move old datasets to artifact folder

**Comment by MartinKahabka** [comment]
think about using another format, were parameter e and x are not used, since the arent used in the pipeline and therefore can be removed
